### ISSUE TITLE
warning: extension used [-Wlanguage-extension-token]

### ISSUE THREAD

**Issue by HiGarfield** [mackron/c89atomic#7]
warning: extension used [-Wlanguage-extension-token] when -std=gnu89.

Caused by inline.

**Comment by mackron** [comment]
What compiler?

**Comment by HiGarfield** [comment]
> What compiler?

https://github.com/HiGarfield/cpulimit/actions/runs/6149726424/job/16686184508

**Comment by HiGarfield** [comment]
Fixed by https://github.com/mackron/c89atomic/pull/8.
